* Quick Links to Documentation

- [[./cube-diagrams][Cube Diagrams]]

- [[./audio-use-guide.org][Audio Documentation]]

- [[./disis-use-guide.pdf][DISIS Use Guide]]

- [[./Reaper-Templates][Reaper Project File Templates]]

- [[./puredata-patches][Pure data Helper Patches]]

- [[./max-patches][Max Helper Patches]]

- [[./motion-tracking.org][Motion Tracking Help]]

- [[./speaker-coordinates/][Speaker Coordinates]]

* What Does This Include?

This repository is for anyone coming to the ICAT spaces. It hosts a wide variety of documentation, patches, and programs for use at ICAT to make your life easier. It can be cloned to your local computer for later use.

It also includes some useful programs and patches for use in the ICAT facilities. Some of this includes Reaper Template files, Max msp patches, and pure data (pd) patches that ICAT has developed in house for use in its facilities. 

If there are changes that need to be made, feel free to make a pull request and we can make the appropriate changes.

* Guidelines for Contributing to the Repository

1. Avoid using spaces in file names. Spaces can make working with git (or in a shell) much harder. Use hyphens instead: This-is-a-file.txt, instead of "This is a file.txt"

2. When making commits, make sure to include enough information so we know what changed from the previous version. Be specific! This will make our lives easier when it comes to documenting our documentation.

3. Pictures for documentation should go in the .imagegit folder for use within the repository.

# Credits

# Include names and/or email addresses here if people feel comfortable doing that.
